### ISSUE TITLE
Random access

### ISSUE THREAD

**Issue by sagnikbanerjee15** [rcanovas/libCSAM#3]
Hello,

I wish to perform random access but I cannot find the executable GetIntervalSAM after compilation. Could you please look into it?

Thank you.

**Comment by rcanovas** [comment]
Hello,
  Thanks for your post. Yes, I forgot to add the GetInterval functions within the make all in the Makefile. I have corrected that now. Otherwise, you can just generate the missing function by calling: make functionName (ex. make GetIntervalSAM)

**Comment by sagnikbanerjee15** [comment]
Thank you for updating the makefile. I was able to compile it but it gave me the following error.

GetIntervalSAM: src/cqual/././../basics/./io.h:79: T cds::basic::LoadValue(std::istream&) [with T = long unsigned int; std::istream = std::basic_istream<char>]: Assertion `in.good()' failed.
Aborted (core dumped)

Any ideas about what might be causing it?

Thanks.

**Comment by rcanovas** [comment]
Given the output it seems that you are passing the arguments in the wrong order, but it is difficult to know without knowing the command line that you are running and the input file. If you can provide me with this information, I may be able to check what is the real cause.

I tried the command on the file that you send me before using ref = 1 (chr1) and positions 1000-10000 and it worked well for me. 

rcanovas@kairos:~/Desktop/libCSAM-master/example$ ./../GetIntervalSAM compress_csam_q_0_m_0_SRR13711353-SRR13711354_SE_0.csam 1 1000 1000000 
Get Interval: 1 [1000, 1000000]
rcanovas@kairos:~/Desktop/libCSAM-master/example$ head compress_csam_q_0_m_0_SRR13711353-SRR13711354_SE_0.csam_inter.sam
2366338_2	16	1	3137	255	8M37530N143M	*	0	0	TTGTTTTGCTTTACAAGACATAGGAAAAGGGAACGAAAAGTAAAGCGCAAATAGCCACTCGATAAGCACCAATGACCATATGGTTCACACAGACATCAAGAGCTTTCTTCACAAGTGCATTCACCGAAGCCATCGCTACATTTGACATCAC	--<-<-<-7--A-A-A7----A-7----)JA-7--FF-7-77---77-F777-7-77-A-7-7--7--F<----F<F-J-7<------77--JAJF<-<-7-JF-<-7------F-FF<----7-777-7-7-7<-<F--F7F77-<<-AA	NH:i:1	HI:i:1	AS:i:129	nM:i:9	NM:i:9	MD:Z:12C11C9C4T7G9T32C0A36C22	jM:B:c,2	jI:B:i,3145,40674	XS:A:-
